
# version: "3.8"

networks:
  appnet:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    image: wordpress:6.4-php8.1-apache
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-app:/var/www/html
    ports:
      - "8081:80" # Optional for local direct WP access
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    env_file: ./server/.env
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - appnet

  client:
    build: ./client
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_WORDPRESS_URL: /blog/wp-json/wp/v2
    restart: always
    depends_on:
      server:
        condition: service_started
    ports: 
      - "3000:3000"
    networks:
      - appnet

  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8085:80"
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_started
      wordpress:
        condition: service_healthy
    networks:
      - appnet

 



# networks:
#   appnet:
#     driver: bridge

# volumes:
#   db_data:

# services:
#   mysql:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: wordpress
#       MYSQL_USER: wpuser
#       MYSQL_PASSWORD: wppassword
#     volumes:
#       - db_data:/var/lib/mysql
#     networks:
#       - appnet
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   wordpress:
#     image: wordpress:6.4-php8.1-apache
#     restart: always
#     depends_on:
#       mysql:
#         condition: service_healthy
#     environment:
#       WORDPRESS_DB_HOST: mysql:3306
#       WORDPRESS_DB_USER: wpuser
#       WORDPRESS_DB_PASSWORD: wppassword
#       WORDPRESS_DB_NAME: wordpress
#     volumes:
#       - ./wp-app:/var/www/html
#     ports:
#       - "127.0.0.1:9001:80"
#     networks:
#       - appnet
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost/wp-admin/install.php"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   server:
#     build: ./server
#     env_file: ./server/.env
#     restart: always
#     depends_on:
#       wordpress:
#         condition: service_healthy
#       mysql:
#         condition: service_healthy
#     ports:
#       - "127.0.0.1:9003:8080"
#     networks:
#       - appnet

#   client:
#     build: ./client
#     environment:
#       NODE_ENV: production
#       NEXT_PUBLIC_API_URL: /api
#       NEXT_PUBLIC_WORDPRESS_URL: /blog/wp-json/wp/v2
#     restart: always
#     depends_on:
#       server:
#         condition: service_started
#     ports: 
#       - "127.0.0.1:9002:3000"
#     networks:
#       - appnet

 