import { Montserrat } from "next/font/google";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import Providers from "@/Providers";
import ConditionalLayout from "@/components/ConditionalLayout";

export const metadata = {
  title: "Enlighten",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} relative`}>
        <Providers>
          <ConditionalLayout>{children}</ConditionalLayout>
        </Providers>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
